### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by ffontaine** [microchip-ung/easyframes#3]
Latest release was made more than one year ago, would we good to get a new one.

**Comment by HoratiuVultur** [comment]
Yes, I will create one in the following days.

**Comment by ffontaine** [comment]
Thanks, I'll use it in buildroot as soon as it is available.

**Comment by HoratiuVultur** [comment]
I have just create a new release.

**Comment by ffontaine** [comment]
Thanks, then I'm closing this issue.
